### ISSUE TITLE
Guard Mode Using Multiple Weapons

### ISSUE THREAD

**Issue by faulsamuel4** [PapaJoesSoup/BDArmory#115]
#when i saw a video on youtube {([_https://www.youtube.com/watch?v=dqj4jyygoFs_]), at 5:52} i was wanting to build a battleship that can fire on its own with multiple weapons firing at once, like both mains and 2ndaries firing on land and sea borne threats, and aa for antimissile and antiaircraft operations.....is there a way to make it happen? ty ^.^

**Comment by gomker** [comment]
This has been on my mind as well as we updated the Guard Mode code - recent updates included targeting improvements to the weapon choices the AI makes. 
Our code refactor will need to occur first to make some of these functions more independent.

**Comment by faulsamuel4** [comment]
ty for the info!

**Comment by TheDogKSP** [comment]
Since AI/Targeting is also one of my high-interest topics, here my 2cents:
(warning, wall of text)

assuming it would be easy to implement after a refactoring/rewrite of BDA, the first question is what is desired *conceptually*.
- how to determine how many targets can be engaged simultaneously?
- can each _type of weapon_ engage multiple targets?
- or can even each _weapon_ engage multiple targets?
- can the same target be engaged by more than 1 weapon simultaneously?
- how to decide, if multiple targets are within engagement range, if to "split fire" onto multiple ones or "concentrate fire" on the biggest/closest threat?


An implementation can become as complex as you like, depending on the concept.
What I would envision is maybe something along these lines:

1. give each weapon an explicit "engagement envelope", which means: I can set a gun in the editor via right-click menu to engage only ground targets, or air targets, of incoming missiles, and at what range (limited by max firing range of the weapon). These settings are then respected by the guard mode during weapons selection.

2. One additional setting in the weapon manager: "max parallel targets". This gives a hard upper limit for how many targets it tries to engage at once.

3. If you strive to make the whole system more complex, then (2) only gives a hard upper limit, but in order to actually select, track and engage multiple targets it would need combat systems (fire control, sensors) to actually track & lock multiple targets.
Luckily, bahamotuD already gave radars the "max locks" settings.
Maybe besides the weapon manager we then have another part, be it called "AEGIS core" or "fire control system", which has a limit on how many targets it can process & engagage.

So, given the above I build a guided missile destroyer with:
- weaponsmanager->max_parallel_targets = 10
- AN/SPY radar with capability to track & lock 6 targets at the same time
- "AEGIS core" with "max_targets" = 20

=> Result: MIN(weaponsmanager_parallel_targets; radar_capabilities; fire_control_capabilities) = MIN(10; 6; 20) => it can engage 6 targets at the same time (limited by radar capabilities).

And now the first problem:
this concept fits maybe quite well to a modern AEGIS area, but what about large WW1 naval battles (no radar, no aegis)...?

**Comment by faulsamuel4** [comment]
mainly, i did have a battleship that i built, but i fitted it with both modern and ww2 weapons, were all aa is modern, and some artillery is also modern, but the hull and other artillery is ww2... i guess that using all aa against missiles and artillery guns against crafts is what i was getting at...maybe the aa vs the missile and parts called 'engines', and artillery vs parts called 'pods' might help?
here is the battleship that i made, just fyi.....just thought that might make it easier to show it:
![screenshot5](https://cloud.githubusercontent.com/assets/24465649/21076249/b73b71aa-bef4-11e6-9ee8-7864eb4180bc.png)

**Comment by gomker** [comment]
@TheDogKSP has this been implemented with all the recent updates - I feel like we are at what was proposed to the greatest extent we could in code at the moement
