### ISSUE TITLE
Physics Range persistence

### ISSUE THREAD

**Issue by Wareagle1** [PapaJoesSoup/BDArmory#14]
In the latest update the physics range no longer stays saved with overall.
For example, if i spawn a ship from the SPH/VAB and set the physics range to 30km then move my ship to the water and spawn another ship via vesslemover. If i then move that second craft beyond 5km and place it then switch back to the first ship and try to switch back to the second ship it says the craft is out of range. When i then go and click set range to 30km again it acts like the ship would when it loads into physics range….blows up.

The work around is to place both ships side by side then set the physics range. Then i can move my target ship beyond 5km and not worry about it getting out of the 30km physics range.

**Comment by DoctorDavinci** [comment]
Does this occur with all your naval vessels or just a specific one that you have been working on?

**Comment by gomker** [comment]
I would suggest renaming this to "Physics Range persistence"  as it could be confused with known issues with loading large vessels exploding due to physics / drag cube issues. 
This is a well known problem with boat builders discussed at length in[ Large Boats Pack](http://forum.kerbalspaceprogram.com/index.php?/topic/133439-113-large-boat-parts-pack/) thread among others

**Comment by jrodrigv** [comment]
Closing this issue, it is now obsolete.
