### ISSUE TITLE
How to get started working on this mod?

### ISSUE THREAD

**Issue by Guard13007** [PapaJoesSoup/BDArmory#145]
I wish to help with development, but have no idea what I need to do to get started other than looking through the code.

What do I need to set up to be able to build and test things before sending in pull requests?

**Comment by jrodrigv** [comment]
@Guard13007 I'm glad you want to help us with BDArmory.
 I can write a guide for you. But I need to know first which your current knowlegde about the tipical concepts and tools: C#, VS, Unity debuggind and mod development

**Comment by Guard13007** [comment]
Assume basic competence with running commands, working in a terminal, programming, but not specifics of the languages/environments. Basically, what version of Unity to install, how to configure it, what version of anything else needed, how to configure, how to test and compile so I can try things before submitting pull requests.

**Comment by jrodrigv** [comment]
Ok. I'm going to try to summarize a list of things.
You will need the following software:

- Unity 5.4.0p4
- Visual Studio 2015.
- Unity extension for visual studio 2015.

Then I recommend using this guide done by @sarbian http://forum.kerbalspaceprogram.com/index.php?/topic/102909-ksp-plugin-debugging-and-profiling-for-visual-studio-and-monodevelop-on-all-os/

It explains how to set up everything in order to debug your code.
