### ISSUE TITLE
Bomb sights not appearing

### ISSUE THREAD

**Issue by IronandCopper** [PapaJoesSoup/BDArmory#150]
When I select a bomb (any bomb, not just the un-guided ones) in the weapon manager, the green circle that indicates where the bomb will land doesn't show up, and even if it does, the green circle is usually directly vertical to the aircraft, witch is clearly wrong.  The only time I've gotten them to show up correctly is when below ~250 meters, far too low.

**Comment by jrodrigv** [comment]
This is issue has been fixed and it will be released with the next release. Thanks!

**Comment by MuricanJeb** [comment]
This happened to me before, all I had to do was reinstall the mod :trollface:

**Comment by Qromodynmc** [comment]
Would you give any info about next release date? Because i've been following issue and it got fixed like 6 months ago, yet there is literally nothing since then. I really hate being "ungrateful" guy but, current state of bd makes me sad, atleast somebody can say "we dont care bda, find something else" then i'd be totally ok.

**Comment by jrodrigv** [comment]
@Qromodynmc No problem, you are not "ungrateful" at all, you are just an ignorant :)

It is very easy to know that "we" the BDA team ( specially me..) have been quite busy working on the next release. 

You just need to go to https://github.com/PapaJoesSoup/BDArmory/tree/support, click on the "601 commits" and check the history, you will see that almost every week we have been performing changes to BDArmory.

So, if you want to play the current dev version of BDArmory, you just need to click on the "Clone or dowload button under the Support branch, delete your BDArmory folder and copy over the Distribution/GameData/BDArmory from the zip file.

However, we will decide when to do the next release because it includes a big feature that requires some documentation to be written for the users like you to understand exactly how it works :)

**Comment by Qromodynmc** [comment]
You're the man! Thank you so much.
