### ISSUE TITLE
Radar range

### ISSUE THREAD

**Issue by TonyDE94** [PapaJoesSoup/BDArmory#170]
Abiility to increase radar range would be needed if possible

**Comment by gomker** [comment]
With the addition of Physics Extender this is something we are looking into again. Some issues to consider for balance 

1) EC Usage for more powerful radar
2) Tracking and locking vs detection

**Comment by Isenderen** [comment]
I am very interested in a radar range extention as well. I currently have an AIM-54 pheonix i built using the procedural missiles mod, but i cant use it to its fullest extent with only a 10km radar range.

**Comment by gomker** [comment]
Radar range has been increased in a feature branch and will be merged into a release after testing

**Comment by Toonu** [comment]
Suggest more like 60km than 40km due to testing of ships over long distances, both guns and missiles. Guns are useless at 20+km, but all modern ships with VLS has ranges over 40km with SM missiles. That 20km more is perfect balance I guess, because small range missiles would fit not at that range, but long range will be able to fire (yes, Patriot, thinking about you. 
Also only large radars should have that long range, still it would be over-horizon battles mostly for ships or SAMs.

**Comment by gomker** [comment]
This will most likely end up being a configuration you can control via the `settings.cfg`

**Comment by jrodrigv** [comment]
@gomker  we have already implemented this  right?. Adding to the next milestone

**Comment by TheDogKSP** [comment]
v1.0.0 released, closing this issue
