### ISSUE TITLE
Penetration and Armor

### ISSUE THREAD

**Issue by Deathpuff12** [PapaJoesSoup/BDArmory#174]
So, I make a lot of tanks. I usually have 3-6 layers of structural plates, depending on the role of the tank. I have noticed that anything above a .50 cal can completely shred the inside of my tank.

Naturally, I decided to do some testing. I made a little platform, with different layouts of armor (in this case, 2x2 structural panels). After each layout I put a wing connector type C, to help me tell if they were actually penetrating.
These are the different layouts, and what was able to penetrate at 2500m:
("" means ditto)
- 3 layers of panels, with 3 layers of slanted panels behind them. Penetrated by all but .50 cal.
- 4 layers of slanted panels. ""
- 7 layers of spaced panels. ""
- 45 layers of panels. Took a moment, but still penetrated by everything but the .50 cal.

(Howitzer completely destroyed the platform)

As you can see, penetration (and armor) is kind of broken right now. A vehicle using a single vulcan turret and no armor can beat a tank using several meters of armor and a huge howitzer. A plane with a vulcan cannon can completely destroy my big, heavily armored ship in a single strafing run.

I think, if possible, you guys should just leave out penetration until it is working, as it makes BDArmory no fun if you want to battle with tanks.

**Comment by Deathpuff12** [comment]
I should also mention that I tried to use a single bullet for each test, but the guns were not accurate at that range, so there might have been a few. Although, I don't think a couple more bullets would really make a difference.

**Comment by jrodrigv** [comment]
Maybe @SpannerMonkey can add more information but from my point of view there is huge power gap between explosive bullets and normal bullets.
 
We need to balance this.

**Comment by SpannerMonkey** [comment]
Re Armor and structural panels,  I have pointed out many times in the BDAc thread and other conversations that as it stands structural panels offer no more protection than any other part and considerably less than some. AT present there is only one mod with working and effective armor  and it's not BDAc  
There is currently a huge disparity between the capabilities of BDAc and the user at large's understanding.  It seems to that very few mod makers are interested in getting up to speed on the changes.
To remedy the current situation the are several courses of action that could be taken  and not one of them is solely reliant on making weapons less powerful, and thereby cripple all the work that was put in on the development of penetration etc

With the correct armor no reduction in firepower is required and the systems in place work very well ( ask any user of SM Armory) when combined,  updated bullets definitions (most cfgs still dont have them and most ammo is without a bullet type )   , penetration and armor work extremely well  .  

It is up to the team to decide how they want to proceed.  Armor has been made available to the team previously  for appraisal (though that version is now inferior to the current arrangement by an order of magnitude)

**Comment by Guard13007** [comment]
@SpannerMonkey Perhaps the solution is to take on development of patches for other mods and stock parts to add armor ratings. If I am understanding you correctly in that everything is ready to go on BD's side, and it's just configs need to be written..

**Comment by SpannerMonkey** [comment]
WIth regard to retro fitting armor modules into  an other part  sadly does not work, The armor relies on a specifically named and rotated transform being at the root of the hierarchy in order to function as it should .
The solution is not to do other modders work for them,  I have already appraised the team of the amount of patches that would be required and it runs into the many hundreds and if you cover all the parts it's in the thousands,.  
As far as being ready to go yes all the BDA code is in place and it appears fully functional,  however without the bullet definitions and armor  it's wasted on the average user, which is sad because it's a whole new world

I  PM'd each weapon maker in turn to tell them of the changes and my suggestions as to how to proceed and as yet not one , I'm aware of.  has changed things in response to  any of the advice.  For example for CAL i submitted a large revision featuring bullet definitions for most common shell and ammo types, a months work or so, over 9 weeks ago and it was swept aside and ignored as irrelevance
Don't see that there's much more I can do,  I'll keep adding to the version of CAL I use in house and with my test group and maybe one day the rest of the military modding community will catch on

I'll  think on some ways to get armor out to the masses, likely reworking something I already have working  to be standalone and tweakscalable and then we'll have to see how it goes

**Comment by flywlyx** [comment]
Armor and penetration has got a great improvement, thanks for the awesome work.
For the current situation, I would suggest BDAc include an armored panel to avoid any misconception that penetration is broken or/and malfunction.
The only issue I have is that armor is taking full damage, which means, the armored turret and non-armored turret is treated the same. Lack of penetration should be added into pooled bullet to define the bullets stay in armor.

**Comment by Deathpuff12** [comment]
So I've been thinking about the armor, and I think it would be cool to add some sort of system like the procedural wings from B9. People could shape them however they want, and it would make building armored vehicles so much easier than it is now. I have no idea how it would be done, but I think everybody would appreciate it.

**Comment by gomker** [comment]
@Deathpuff12  Spanner has some parts that are coming out that support tweakscale soon to allow for some of what you requested. As for making it "procedural" takes a bit more work as the parts that indicate armor are part of the part layers. Essentially either we (BDAc Team) make a procedural part system OR B9 maintainers implement our layers for armor. Both are not ideal solutions from a coding perspective at the moment.  

This is all very new and work in progress and we think with the parts coming with tweakscale should cover most of what you will need to properly armor a vessel. Also as Spanner pointed out , bringing other devs to the table takes time for adoption.
