### ISSUE TITLE
Targeting Pods not working (No Laser Guided Missile Lock)

### ISSUE THREAD

**Issue by HooHungLow** [PapaJoesSoup/BDArmory#187]
I recently upgraded to the latest version of BDA, and for some reason the Targeting Pods are not working correctly, after selecting and lasing a target there is no "lock on ring", and if a target is in range and a missile fired, it just flies into the ground. 

Any help would be appreciated. 

Thanks!

**Comment by SleepyGuardian** [comment]
I haven't experienced laser guided munitions not tracking targets, however, I have found that the AI will not utilize turrets that fire TOW missiles, and it wont use targeting pods for laser guided GBUs.

**Comment by gomker** [comment]
Hey guys, since we are in an update cycle, 1.2 to 1.3, it is important to be specific in what versions you are running :

When reporting issues please provide the following information:

- Version of KSP
- Version of BDA
- OS Build and Version
- Link to a full KSP log if reporting a problem

[See this for more information
](http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/)

Also note that targeting can be quite complex, have you read the in-game KSPedia that illustrates targeting?  

@SleepyGuardian We have also recently updated the targeting methods for all missiles, in-game if you right click on the missile it will have options for engaging air, ground or missile. Please check these values as the defaults may not be correct for what you expect the AI to engage.

**Comment by TheDogKSP** [comment]
In addition to the information requested by gomker, please state your scenario when you encounter the problem: are you trying to target a vehicle on land, or a ship on the water?

**Comment by SleepyGuardian** [comment]
Yeah, sorry about that. Im using ver. 0.2.1 on KSP 1.2.2. Scenario is an air vehicle against a ground target using a laser guided gbu and targeting pod. The other is a ground based turret targeting a ground vehicle using a targeting pod and standard TOW launcher.

**Comment by Webwolf1980** [comment]
Hey guys, I'm using ver. 0.2.1.1 on KSP 1.3.0.I have  no "lock on ring" while using Targeting Pods,and the missiles  just flies into the ground too(tested all laser guided missiles in a 1500m air to ground Scenario)
also I found GPS guided weapons (AGM-86C,RBS-15)are not working correctly,they didn't home in on the target coordinate,they just fall like a unguided bomb....

**Comment by jrodrigv** [comment]
Do you have PhysicsRangeExtender installed?

**Comment by Webwolf1980** [comment]
Yes I have PhysicsRangeExtender v1.4.0 installed and enabled,
I can hit and destroy targets with guns and connons

**Comment by jobaluke** [comment]
I have also had this issue with version 0.2.1.2 on KSP version 1.3 the laser guided missiles will not go to the designated target with the both the AGM-114 Hellfire and the AGM-54 Phoenix and there being no lock on ring for the target ball.

**Comment by gomker** [comment]
#216 May be related

**Comment by gomker** [comment]
Latest release has fix implemented
https://github.com/PapaJoesSoup/BDArmory/releases/tag/v0.3.0.0
