### ISSUE TITLE
AAM modular guidance causing weapon overheat?

### ISSUE THREAD

**Issue by ChiefRatcliff** [PapaJoesSoup/BDArmory#248]
Testing a SAM, AGM/STS mode works well but whenever AAM is selected it overheats after traveling about half a kilometer.  Same results with / without warhead, no build up of heat either.  It just spontaneously explodes.

**Comment by jrodrigv** [comment]
OK. If the missile is exploding is because it is doing a controlled 'autodetonation'. That means the missile is 'missing' its target. 

A missile will consider its target a 'missed' if:
The missile has no thrust (active engines), the angles between the missile  and the target are greater that the boresight and the distance between the missile and the target is always increasing

**Comment by jrodrigv** [comment]
Would you mind to attach the KSP. log file when this is happening?

**Comment by ChiefRatcliff** [comment]
[KSP.log.txt](https://github.com/PapaJoesSoup/BDArmory/files/1164905/KSP.log.txt)

**Comment by jrodrigv** [comment]
I have reviewed the logs. The missile was performing an auto-detonation because it missed its target
