### ISSUE TITLE
nothing is working

### ISSUE THREAD

**Issue by evilwu** [PapaJoesSoup/BDArmory#264]
Whenever I use a gun it doesn't shoot. 
Whenever I use a missile it doesn't shoot. (If it does on the very, very rare chance, it just disappears)
Whenever I use a bomb it doesn't drop. (If it does on the very, very rare chance, it just disappears)
Not all the ammo is showing up along with some other stuff.

Pretty much, nothing is working for me. I'm using the latest version of the mod, and of ksp.

**Comment by TheDogKSP** [comment]
Based on this information my crystal ball tells me that your install is messed up.
Please check.

If you need a more detailed analysis, please submit a KSP.log with "debug labels" turned on in the BDA settings, and a scenario.sfs where the problem occurs.

**Comment by PapaJoesSoup** [comment]
In addition, please refer to the Wiki above.   In the first page you will see instructions in how to troubleshoot your installation.   Please follow those instructions.

**Comment by evilwu** [comment]
I reinstalled the mod and troubleshot it. Some of the weapons are working, however missiles, bombs, some cannons and some turrets still are giving me a problem. Missiles and bombs won't fire with action groups, and when I manually fire them they just disappear. Cannons and turrets just won't fire even with the correct ammo loaded.

**Comment by PapaJoesSoup** [comment]
Not to be difficult, but please follow TheDogKSP's instructions above mine... we cannot help you if all you tell us is "its not working".  Even telling us what is not working, without something "substantial" like a log helps us very little.  We want to support you, but you need to "help us help you".  part of the troubleshooting instructions include log files, steps to reproduce, parts involved, potentially a save game and crafts involved.

Thanks for using BDA, and we hope to "get you fixed up".

**Comment by evilwu** [comment]
Where is the KSP.log, I can't find it.

**Comment by PapaJoesSoup** [comment]
KSP.log is in the game root folder.
Output.txt is in the KSP_x64_Data folder.

The question however, leads me to believe you did not thoroughly review the troubleshooting instructions, as this information is contained within...

I'm in no way am trying to be rude.  Please consider that The BDAc team spends hundreds of hours (for free!) trying to make BDAc great.  If those that wish to use the Mod do not spend just a little time to help us, it takes away from our efforts to continue making the mod great, and could be considered "selfish".  

I hope that helps to put our position into perspective, and please try to provide a proper issue report, based on the instructions contained in the Forum OP (and associated links contained therein)

**Comment by evilwu** [comment]
I understand and am appreciative that you guys spend a lot of time on the mod and helping out the community. I did do as instructed, TheDogKSP's stated; 

>Based on this information my crystal ball tells me that your install is messed up.
 Please check.

If you need a more detailed analysis, please submit a KSP.log with "debug labels" turned on in the BDA settings, and a scenario.sfs where the problem occurs.> 

I reinstalled the game following all instructions to make sure it was installed correctly. And am now following his second piece of advice, which would be sending a KSP.log. I didn't know where that was so I asked. I've also visited the current forum for the mod several times and have done everything suggested there. If there is anything else I can do please let me know.

here's the KSP.log from KSP_x64_Data
[output_log.txt](https://github.com/PapaJoesSoup/BDArmory/files/1195770/output_log.txt)

As I mentioned before whenever I drop a bomb, or fire a missile it disappears. However this disappearing effect thingy also happens when I decouple things from a plane or rocket. It also occurs when I do a EVA with a Kerbal. I also seem to be missing some items (though I'm not completely sure). 

My apologies if I've come off as rude or anything, I just really have no clue with ksp mods. I know how to download them, but I really have no clue how to do detail analysis with ksp mods. I'm not sure what to do, but I really like the premise of the mod and really want to play around with it. Again, anything else I can do please let me know.

**Comment by PapaJoesSoup** [comment]
Thanks!  A log is worth more than its weigh in gold...

your problem is in this section here.  Please note that all Mods (ALL MODS) Go into the GameData folder.

So,

Non platform assembly: E:\SteamLibrary\steamapps\common\Kerbal Space Program\Plugins\GameData\KSPWheel\Plugin\KSPWheel.dll (this message is harmless)
Non platform assembly: E:\SteamLibrary\steamapps\common\Kerbal Space Program\Plugins\GameData\PhysicsRangeExtender\Plugins\PhysicsRangeExtender.dll (this message is harmless)
Non platform assembly: E:\SteamLibrary\steamapps\common\Kerbal Space Program\Plugins\GameData\TweakScale\plugins\Scale.dll (this message is harmless)
Non platform assembly: E:\SteamLibrary\steamapps\common\Kerbal Space Program\Plugins\GameData\TweakScale\plugins\Scale_Redist.dll (this message is harmless)
Non platform assembly: E:\SteamLibrary\steamapps\common\Kerbal Space Program\Plugins\Mk2Expansion-1.7.7\GameData\ModuleManager.2.8.1.dll (this message is harmless)
Non platform assembly: E:\SteamLibrary\steamapps\common\Kerbal Space Program\Plugins\Mk2Expansion-1.7.7\GameData\InterstellarFuelSwitch\Plugins\InterstellarFuelSwitch.dll (this message is harmless)
Non platform assembly: E:\SteamLibrary\steamapps\common\Kerbal Space Program\Plugins\Mk2Expansion-1.7.7\GameData\InterstellarFuelSwitch\Plugins\MiniAVC.dll (this message is harmless)
Non platform assembly: E:\SteamLibrary\steamapps\common\Kerbal Space Program\Plugins\Mk2Expansion-1.7.7\GameData\InterstellarFuelSwitch\Plugins\Scale_Redist.dll (this message is harmless)
Non platform assembly: E:\SteamLibrary\steamapps\common\Kerbal Space Program\Plugins\MP Game Data\GameData\Firespitter\Plugins\Firespitter.dll (this message is harmless)
Non platform assembly: E:\SteamLibrary\steamapps\common\Kerbal Space Program\Plugins\MP Game Data\GameData\Maritime Pack\Plugins\MiniAVC.dll (this message is harmless)
Non platform assembly: E:\SteamLibrary\steamapps\common\Kerbal Space Program\Plugins\MP Game Data\GameData\MPUtils\Plugins\MPUtils.dll (this message is harmless)

Are all incorrectly installed.

They need to go here:  E:\SteamLibrary\steamapps\common\Kerbal Space Program\GameData.

So, for example:  
Non platform assembly: E:\SteamLibrary\steamapps\common\Kerbal Space Program\Plugins\MP Game Data\GameData\Maritime Pack\...  (The folder Maritime Pack is the important one here)

Should be:  
Non platform assembly: E:\SteamLibrary\steamapps\common\Kerbal Space Program\GameData\Maritime Pack\...

So what you have done is extract the GameData folder of each of these mods into your 
E:\SteamLibrary\steamapps\common\Kerbal Space Program\Plugins folder.

You will need to move those folders to where they should be.  Notice that Squad places all their stuff in:
E:\SteamLibrary\steamapps\common\Kerbal Space Program\GameData\Squad...

Hope that helps!

**Comment by evilwu** [comment]
*sigh* I intended on putting them in gamedata, and then I got distracted and never did. I feel so stupid xD
Everything is working perfectly now.

Thanks again for your help, I really appreciate it. My apologies for not being descriptive or really helpful with my issue, but thanks for your help :)

**Comment by PapaJoesSoup** [comment]
Glad you are up and running.  Closing issue.
