### ISSUE TITLE
Enhancement - Allow the Weapon Manager to turn on the ECM when in guard mode

### ISSUE THREAD

**Issue by DoctorDavinci** [PapaJoesSoup/BDArmory#27]
Currently the Weapon manager doesn't turn on an attached ECM when in guard mode

**Comment by TheDestroyer111** [comment]
Good idea. I also think it should use ECM only at certain distances from an enemy (AFAIK, and according to my tests, ECM jammer does nothing at shorter ranges). So if all loaded enemies are at short range, the jammer should be disabled to conserve electricity.

**Comment by Feni85** [comment]
If I remember correctly, the radar in BDA works by making a small black and white picture of the craft it is targeting (64*64px something or less) and counts the amount of black pixels to determine a lock or not. The ECM reduces the amount of pixels in the targeting picture and therefore reducing the range of detection but not making it zero. The less sensitive the radar is, the greater the effect of ECM. 

Enabling the ECM in guard mode would be natural behaviour in combat and would therefore be a good enhancement. Disabling the ECM at short range isn't normal behaviour in combat since there might be another foe at range that you haven't detected yet (other than the one that is close, perhaps using ECM themselves).

**Comment by gomker** [comment]
How this works now - Added a function along side the fire chaff in Guard Mode. Will enable the ECM Jammer for 10 seconds at a time. Will review further for balance and effectiveness in combat.

**Comment by TheDestroyer111** [comment]
@gomker , it shouldn't always be ten seconds. If ECM actually *may* do something at short range, then it's better to use it depending on some sort of equation based on electricity generation, range from target, and whether the target can lock on properly... Thoughts?

**Comment by gomker** [comment]
This was just the first pass on implementing it, so quick and dirty.  What I did was add a function at the same time the Gaurd AI was to fire chaff, this way I didn't need to write any more logic than just activating it.
Reason why I went with 10 seconds is the chaff fires at an interval, so it was toggling the ECM like crazy, this was just a temp work around.

My thoughts were 

1) figure out the right balance on the ECM - as you have noted it sometimes does not do anything useful
2) put better logic to let the AI fire it properly based on EC drain

I started this issue https://github.com/PapaJoesSoup/BDArmory/issues/84 to talk about the ECM balance.
