### ISSUE TITLE
Bullet FX issue + Over penetrate issue

### ISSUE THREAD

**Issue by MuricanJeb** [PapaJoesSoup/BDArmory#286]
##### ISSUE TYPE

 - Bug Report   (Something is broken)

##### KSP and BDA Version

1.3

1.3

##### OS / ENVIRONMENT
PC, Windows 10

##### SUMMARY
When 7.92mm bullets penetrate parts of my aircraft, the bullet just stops as soon as it exits the part, then it follows me around. Sometimes the bullet will return to normal and fly away as normally. Sometimes the bullet will penetrate my plane as normal. This issue sometimes happens with the KSC buildings. Also, I noticed that the 7.92mm bullets from this part pack I am using (top secret weapons pack) ALWAYS penetrate the parts of my plane. I had a heavy fighter intercept a bomber, and I encounters both of these issues. I tried again, but the issues are still there.

##### Log Files
[KSP.log.txt](https://github.com/PapaJoesSoup/BDArmory/files/1235768/KSP.log.txt)

**Comment by MuricanJeb** [comment]
@DoctorDavinci I noticed the issue actually goes for the SM Armory lewis MG
So I played some more ksp, the issue happened, i checked the KSP.log and it says bullets are failing to load. The full log file will be uploaded to the front page of this now.

**Comment by MuricanJeb** [comment]
Any help please?

**Comment by SpannerMonkey** [comment]
I have checked the lewis guns in SM Armory and find them functional. For ref they actually use 7.7x56 not 7.92. I can see from your log that all the BDA bullet and ammo defs are loaded, bullets not being found can also be caused by cfg errors or changes made by MMpatches
Also noted in your log, that the saved craft you are using are compromised by being full of errors due to part cfg changes over time. ( changes in parts do not transfer to saved prefabs)  I strongly suggest, as these errors cause issues, that you rebuild or use newly constructed craft to perform testing. Experience has shown that lots of little errors can combine to cause other features and systems problems

**Comment by MuricanJeb** [comment]
I built a tank, used the 7mm guns i used, but the issue is still here.
I guess i'm gonna have to reinstall ksp, and rebuild everything from scratch 😞
And I will also have to hope that someone else will be able to make a weapons pack of wwii weapons 😕

**Comment by NextStarIndustries** [comment]
Wanted to make a quick correction here, there are a few WWII weapon mods out there that currently work and yes there are a few that haven't been updated yet. A quick Google search will lead you to them. My mod has a couple WWII weapons and works with the current version of BDAc. I believe SpannerMonkey has a few WWII weapons in his mods that work with the current version of BDAc.
My point being there are in fact WWII weapon mods available that are compatible and play quite nicely with the current BDAc version.

**Comment by MuricanJeb** [comment]
So I finally found out the issue.
The weapons had some wrong stuff in the cfgs.
