### ISSUE TITLE
Missiles don't kill missiles

### ISSUE THREAD

**Issue by riccardocagnasso** [PapaJoesSoup/BDArmory#289]
##### ISSUE TYPE
 - Bug Report   (Something is broken)

##### KSP and BDA Version

1.3.0

0.3.0

##### OS / ENVIRONMENT
Windows 64 bit

##### SUMMARY
Anti air missiles don't kill other missiles. If you fire AMRAAM missile to a cruise missile, the AMRAAM will chase the cruise missile correctly and explode near it, but no damage will be actually done.

##### STEPS TO REPRODUCE
1. Fire a cruise missile
2. Target it in the radar
3. Fire a lot of AMRAAM at it

**Comment by gomker** [comment]
@riccardocagnasso  have you set the missiles engagement options to "Engage Missile" in the VAB.
By default the AMRAAM is not set to true. I would also suggest using the PAC3 as it is designed for anti-missile capabilities.

**Comment by jrodrigv** [comment]
I have done some testing using AMRAAM against AGM missiles and depending on the speed, angle and distance the AMRAMM can missed the missile or not. 

I will do more testing using cruise missiles.

**Comment by riccardocagnasso** [comment]
It doesn't seem to me that it "misses".
The explosion is quite near.

**Comment by jrodrigv** [comment]
Then I think it can be related with an issue regarding explosion and blast radius not doing the expected damage.

**Comment by NextStarIndustries** [comment]
@riccardocagnasso I have been testing your scenario repeatedly for over an hour and I have failed to reproduce your issue. I'm using stock BDAc weapons to run test. I have only missed a few times, 2 out of 30, when firing the AMRAAM at a cruise missile and of course it didn't destroy it when it missed. Most of the time it doesn't miss and the cruise missile is destroyed every time, well 28 out of 30. As @jrodrigv  stated I seem to miss more of the AGMs then the cruise missiles, because of speeds and angles, but when it doesn't miss the AGMs are destroyed every time. I missed 8 out of 30. What do you have set for the detonation distance override? I'm using 0 and like I said I fail to reproduce your issue even slightly.
@jrodrigv I'm not seeing any issues with the AMRAAM and it's working as expected, unless I'm doing something different from others.

**Comment by riccardocagnasso** [comment]
Sorry i failed to reproduce the bug myself. I don't know if a was drunk or played with some strange setting.
