### ISSUE TITLE
[Feature Request]: 'helicopter' mode for AI pilot #21

### ISSUE THREAD

**Issue by Nerfclasher** [PapaJoesSoup/BDArmory#29]
In my head this seems simple, but I'm sure that it's far from the truth.

But the idea in my head was to simply use throttle for climbing, instead of pitch, while in 'helicopter' mode. Also a decrease in 'sensitivity' for roll while preforming maneuvers, preferring yaw over roll at least.

(Please over look any spelling mistakes... I've been awake for FAR~~~ too long...)
from https://github.com/BahamutoD/BDArmory/issues/21

**Comment by Feni85** [comment]
This seems a complicated request since the interaction of throttle and pitch causes changes in both vertical and horizontal velocity in a helicopter (and we're not even talking about blade pitch which firespitter rotors don't have). Each craft will react differently to the interplay of these variables. 

Perhaps giving the craft a fixed forward pitch of lets say 20 degrees (or making this a selectable setting) and only influence throttle by AI to would make this workable. I'm not into coding, but I do understand this could be quite a lot of work at BDA foundation level. ;-)

**Comment by gomker** [comment]
I will second @Feni85  comments there. I build a few helicopters and have recently started using Throttle Controlled Avionics. While it works perfectly with some craft I have some its a nightmare to get working right due to the design of craft. 

I will volunteer to test out functionality - I would hook up with the guys who do TCA and see if they would collaborate. I bet they have figured out quite a few things about how this could work already.

**Comment by tetryds** [comment]
Making a controller that keeps a helicopter stable is not hard, should work straight away with a controller overhaul which is much needed on BDA.
However the AI should be tricky, if you attach a fixed weapon to a helicopter aiming will affect its flight, for instance aiming up to hit a target making the craft accelerate backwards and down.
Throttle is also complicated, using a solution from a hovering mod that already works should be the best option, giving it 20 degrees of pitch would make it constantly fly forward, it kinda kills the point of having a helicopter.
It would be interesting though, I support the idea but I wouldn't give it the highest of the priorities now.

**Comment by KerbalPete** [comment]
In order to move forwards you must pitch forward and balance this angle with the thrust of the rotor to maintain altitude. It's a totally different problem from flying an aircraft as it is almost like driving a land vehicle but with a vertical component.
I think that first a land vehicle AI should be built and the current system simplified. The AI is great but it is too messy on the the user side to set up which would make multiple kinds of Ai a total eyesore.
I think the system should make more assumptions about how the aircraft will fly,perhaps based on weapons. It would automatically reduce the aggressiveness of turning and speed in a heavy bomber for example. The front end for AI is too much to look at already and should be simplified.

**Comment by colmoni** [comment]
I've posted extensively on the original BDA thread about VTOL AI:

http://forum.kerbalspaceprogram.com/index.php?/topic/76926-11-bdarmory-v01101-compatibility-fixes-apr-23/&do=findComment&comment=1986621

http://forum.kerbalspaceprogram.com/index.php?/topic/76926-11-bdarmory-v01101-compatibility-fixes-apr-23/&page=165#comment-2085169

http://forum.kerbalspaceprogram.com/index.php?/topic/76926-11-bdarmory-v01101-compatibility-fixes-apr-23/&page=196#comment-2133851

http://forum.kerbalspaceprogram.com/index.php?/topic/76926-11-bdarmory-v01101-compatibility-fixes-apr-23/&page=275#comment-2421202

**Comment by gomker** [comment]
Stale conversation, moving to #354
