### ISSUE TITLE
Create a ground launch version of the AGM-86 Cruise Missile

### ISSUE THREAD

**Issue by DoctorDavinci** [PapaJoesSoup/BDArmory#31]
Launching an AGM-86 from the ground results in the missile not achieving enough forward momentum to attain flight

Adding a ground launch capable version would fix this ... Perhaps adding an SRB, or something along those lines, to the missile would allow for enough forward momentum to achieve stable flight

Video of the issue can be found here: [https://www.youtube.com/watch?v=gCTLUfpo_XI](url)

**Comment by TheDestroyer111** [comment]
LOLROFL.
There is no ground launched variant of the AGM-86 in reality. (The other name for AGM-86 is ALCM, which stands for Air Launched Cruise Missile, NOT for ground launched...) If you want to launch a cruise missile from stationary or slow moving vessel, use the RBS-15.

**Comment by PapaJoesSoup** [comment]
Don't ever let realism stand in the way of a good blast...  :)

**Comment by TheDestroyer111** [comment]
But... If we made another ground-launch-capable cruise missile, we would have to add one more air-launched cruise missile. It's not only for realism, it's also for balance. This way, a long range subsonic cruise missile is not as easy to use as lego bricks (just like other bda missiles aren't). And the RBS 15 is kinda shorter range (due to some glitch probably, because you can again lengthen it with a plane as explained in #16 ), but supersonic and easier to launch.

**Comment by gomker** [comment]
I would agree with @TheDestroyer111 on this one.  Other Weapons pack makers have started to create other missiles to fill these roles

[P.E.W](http://forum.kerbalspaceprogram.com/index.php?/topic/105974-wip105-r11-pew-a-bdarmory-addon/) has a ground launch capable Tomahawk 

[Boomsticks](http://forum.kerbalspaceprogram.com/index.php?/topic/133074-boomsticks-a-bdac-weapons-expansion-now-with-ned-and-ost/) has a ground launched Harpoon with matching turrets. Also has two long range Anti-Ship missiles

**Comment by DoctorDavinci** [comment]
This seems pretty real ..... [https://en.m.wikipedia.org/wiki/BGM-109G_Ground_Launched_Cruise_Missile](url)

**Comment by PapaJoesSoup** [comment]
Doc, your link is bad...

**Comment by TheDestroyer111** [comment]
This (tomahawk) is a toootally different missile. I think all we have to do now is just fixing the RBS-15 so that it has always the same range - right now it explodes in less than 10 kilometers when focus is on the stationary launch vessel or on the missile itself, but if it is followed closer than 5km by a plane (with focus on the plane) one can extend its range. This enhancement will be no issue once the RBS-15 has its range fixed. Remember that the RBS-15 in reality (and it looks like so in BDA too) uses a turbojet sustainer engine.
However, there is one enhancement that could be done to cruise missiles. The RBS-15 is not supersonic in reality. However, I don't know of any real missile similar enough to the BDA RBS-15, so screw it.

**Comment by Feni85** [comment]
As other people also commented in the forum, I think BDAc should focus on being an excellent framework for other weapons packs to function. :-) Perhaps you can make BDAc modular with a core pack (only framework), basic (current weapons included) and experimental/full (go nuts).

**Comment by SpannerMonkey** [comment]
This one should be closed, all that needs to be said has been and feelings are well known.

**Comment by gomker** [comment]
Sounds good. I was trying not to close unless very obvious it was done or if Two members confirm it done.
