### ISSUE TITLE
AMRAAM range is glitched

### ISSUE THREAD

**Issue by TheDestroyer111** [PapaJoesSoup/BDArmory#33]
When firing an AMRAAM at below 5 km, the missile usually works properly. However, when firing from above 10 km, switching away from the launching vessel makes the missile explode a few seconds after switching to it, before it reaches its target. Can someone check if this is not just my issue? My BDArmory is in a bad environment as @DoctorDavinci pointed out.

**Comment by jrodrigv** [comment]
Did you check if the same happens without switching vessels?

**Comment by DoctorDavinci** [comment]
@TheDestroyer111 - I am unable to reproduce the results you are reporting.

Here is the video: [https://youtu.be/ir2K7PchNYI](url)

As I stated before, BDAc is compiled for KSP v1.1.3 ....  This is very likely due to your KSP install not being compatible with this mod as you stated that you are running KSP v1.1.0 which is known to have tons of bugs (hence the updates that brought us to KSP v1.1.3)

Update your KSP install to 1.1.3 and I am sure you will find that these issues you are raising will no longer be issues
