### ISSUE TITLE
Explosive Reactive Armor functionality

### ISSUE THREAD

**Issue by lancefoxcia** [PapaJoesSoup/BDArmory#356]
With the new system of Armor updates to BDAc. I was wondering if there could be a way to implement Modern day E.R.A systems into KSP.

https://youtu.be/t459NbF5Vek?t=1m26s

**Comment by PapaJoesSoup** [comment]
It would be a new armor type.  Fundamentally it could be done within the existing framework. But will take some additional code to handle the eeactive blast and subsequent force mitigations.  Additionally, some additional fx needs to be implemented.  I will defer to @jrodriguez, but it is certainly d doable concept with the new framework

**Comment by jrodrigv** [comment]
Yes. I think with current framework it would easy to implement an special
Explosive Part module to react against a collision or on proximity.

El 8 nov. 2017 7:38, "Joseph Korinek" <notifications@github.com> escribió:

It would be a new armor type. Fundamentally it could be done within the
existing framework. But will take some additional code to handle the
eeactive blast and subsequent force mitigations. Additionally, some
additional fx needs to be implemented. I will defer to @jrodriguez
<https://github.com/jrodriguez>, but it is certainly d doable concept with
the new framework

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PapaJoesSoup/BDArmory/issues/356#issuecomment-342724729>,
or mute the thread

**Comment by gomker** [comment]
in https://github.com/PapaJoesSoup/BDArmory/releases/tag/v1.2.1.4 release
