### ISSUE TITLE
Guard Mode - Allow weighted priority to Anti-Air

### ISSUE THREAD

**Issue by gomker** [PapaJoesSoup/BDArmory#36]
The Guard mode will at times use the wrong weapon for anti-air.
Example, place a cannon and a Goal keeper on the same craft and enable Guard Mode.
The cannon will fire at the incoming craft and the Goal Keeper will not fire at all.

Is there a way for the Guard mode to use more than one weapon and prioritize targets, i.e. the priority should be incoming missiles.  This may need to be weighted in some way in the configuration of each weapon.

**Comment by TheDestroyer111** [comment]
The autopilot and guard mode stuff are a field for cosiderable expansion. I think it should be possible to configure it by the player for guard mode to use certain weapons for certain roles, and with a certain priority for different weapons (like when one gun is out of ammo).

**Comment by jrodrigv** [comment]
I really think we need this, From an user point of view this is bug because is not expected behaviour and it doesn't make sense at all. I will tag this as a bug even knowing this is an enhancement.

**Comment by gomker** [comment]
I have not dug into the code much yet, but does it allow for the weapon manager to use more than one weapon at a time. From observation it does not seem to be the case. 
My thought was to have one targeting group for Anti-vehicle and One for Anti-Missile that would key off a part config label, or maybe GUI config. I.e. Marking GoalKeeper as Anti-Air and would be used for Anti-Vehicle only if all Anti-Missile weaponry was out of ammo or non existent.

**Comment by TheDogKSP** [comment]
I ran into similar topics recently building an AEGIS Frigate with a multitude of weapons.
Things I ran into:
- Main naval gun instead of CIWS shooting at incoming Missiles
- RIM Missiles not used for intercepting incoming Missiles at medium range
- RGM Harpoon (GPS guided) launched at Long range at incoming Missiles
- RGM Harpoon full complement fired at once at target, even though maxMissilesTarget is set to 1 or 2

Some things can be solved with clever parametrisation of the guard mode and the weapons:
- I gave the naval gun a very low max pitch, and set "only fire in range", so it is not used for Close-in AA defense. Now guard mode properly selects the CIWS.
- carefully set Gun range, so that the CIWS only enagages if below minimum engagement range of the RIMs
- to fix launching all Harpoons at once, and especially prevent them being used to target other missiles, I made changes/enhancement in the existing code. At least it works now for me.

=> I am reluctant to submit a pull request, however, since I have the feeling I made some "wild changes" in the code, without proper understanding of how everything works.
@jrodrigv: what is your opinion on that? I am of course very willing to contribute to the Project, just dont wanna mess up the somewhat-messy codebase even further... ?

**Comment by PapaJoesSoup** [comment]
Just my thoughts...
Wouldn't hurt to submit the pr so we cam look at the changes.

Given we will be rewriting the code, I don't think you can "mess it up" too much more. :)

@jrodrigv,  thoughts?

**Comment by TheDogKSP** [comment]
OK, i created a PR for your review.
It also includes a convenience feature I had implemented for myself: right-mouse-button detail information in the VAB/SPH, for parts guns, missiles and radar. I didnt want to have another window open looking at config files all the time...

PR is against master, not support, sorry for this, but I am still on 1.1.3.

**Comment by gomker** [comment]
Changes merged. Closing this for now to cleanup issues - @TheDogKSP Thanks for the contribution, I look forward to collaborating on this further.
