### ISSUE TITLE
Weapons cause NRE when trying to fire without weapon manager

### ISSUE THREAD

**Issue by jediminer543** [PapaJoesSoup/BDArmory#364]
##### ISSUE TYPE
 - Bug Report 

##### KSP and BDA Version

```
1.3.1

BDA:1.0.0
```

##### OS / ENVIRONMENT
Windows

##### SUMMARY
When trying to fire a gun without a weapon manager, the debug console fills with NRE's and the weapon doesn't fire

##### STEPS TO REPRODUCE
Attach gun based turret with no weapon manager, press Alt-F12, go to console then try to fire.

Repeat with weapon manager and compare difference.

**Comment by DoctorDavinci** [comment]
Confirmed ... However this is to be expected when using BDAc as it is clearly explained in the KSPedia as well as on the wiki (not to mention the many references in the BDAc thread) that you will require a weapon manager for the weapons to work

This is due to how the whole of BDAc works as the guns require a weapon manager to operate

Solution is to place a weapon manager on your craft else they will not work as stated on the tin

**Comment by gomker** [comment]
As doc mentioned without a Weapon Manager nothing will work properly, this is by design.
