### ISSUE TITLE
no radars are appearing in parts menu

### ISSUE THREAD

**Issue by coltenmfr** [PapaJoesSoup/BDArmory#474]
i am running ksp 1.4.1 btw

**Comment by DoctorDavinci** [comment]
BD Armory Continued is not compatible with KSP v1.4.1 ... the lastest release is only compatible with KSP v1.3.0 and 1.3.1

**Comment by cole238** [comment]
So when will BDac be compatible with 1.4.1?

**Comment by NextStarIndustries** [comment]
@cole238 I'm not answering for the Team here I'm just letting you know I had some code not related to BDAc that had over 300 changes because of the KSP update so I could only imagine what these guys/gals could be dealing with. They will release it when it's ready to be released and not any sooner. It will be worth the wait though so just be patient.

**Comment by jrodrigv** [comment]
@cole238 we don't know the answer. Thanks @NextStarIndustries  for explanation.
