### ISSUE TITLE
bullets pass through everything

### ISSUE THREAD

**Issue by drexw** [PapaJoesSoup/BDArmory#482]
##### ISSUE TYPE
 - Bug Report   (Something is broken)

##### KSP and BDA Version

1.3.1

latest (1.1.0)

##### OS / ENVIRONMENT
windows 7

##### SUMMARY
bullets go through e v e r y t h i n g mid flight
kerbin,other crafts,etc etc

##### STEPS TO REPRODUCE
step 1:create a craft capable of shooting and flying
step 2:shoot

**Comment by Gedas-S** [comment]
@drexw You're probably missing module manager, or have an incompatible version. Double-check that, and if it turns out that is not the problem, we'll need logs to be able to help you. Cheers. ;)

**Comment by drexw** [comment]
nope,i've got the latest module manager,weapons work on land vehicles perfectly fine,im assuming it may be because of the physics range mod,but here are the logs:
http://rgho.st/6ZNQGMGHn
http://rgho.st/private/6T9f6P46L/77050e1fc94c1e8653dad8e54dc43979
just press "скачать" on the blue button on the bottom of the page,im russian and im too lazy to use any other file hosting site

**Comment by Gedas-S** [comment]
You can just upload them directly to github, but no worries, it worked just fine.

Bullets passing through a vessel is usually due to problems with the hitpoint tracker module. Looking at the logs they are not throwing any errors, so:

1. I see you have two module managers. Usually it is recommended to have only one (keep the newer one), but I'm not sure if that is the problem. No harm in fixing it though.
2. Can you check if the parts have a hitpoint bar in the right click menu? Perhaps they have it on the ground and then it disappears when you go up in the air? Perhaps you have two (because of two MM)? :)
3. If it's none of that, it's likely some sort of bug due to localization, you're using the Russian version, right?

**Comment by drexw** [comment]
1. fixed it,still happens
2. yes,they do have a hitpoint bar,and only one
3. no,im using the english latest version

**Comment by drexw** [comment]
also it goes through everything,including kerbin and other buildings

**Comment by Gedas-S** [comment]
I meant that KSP is in Russian. I can see it is from the logs. I tried firing up the Russian version, and the bullets work fine. So I'm not sure what is wrong. It could be corrupted files, could be another mod causing issues. Could be a BDA bug, but until we know what it is, fixing it is problematic. The logs don't show any errors. :(

Unfortunately, I'm not able to help much at this point. 

You can always try reinstalling KSP (maybe even switching to an English version to test), redownloading BDA, and checking if it works. If it does not, try a different BDA version (there are older versions which are 1.3.1 compatible). If it does, install your other mods one by one, and see which one breaks it.

It's your decision if it's worth it, though. :)

**Comment by drexw** [comment]
too lazy,i prefer on ground combat,although,big thanks for the overall support
