### ISSUE TITLE
Flares following Aircraft

### ISSUE THREAD

**Issue by Survivalist19** [PapaJoesSoup/BDArmory#518]
ISSUE TYPE

 - Bug Report 

KSP and BDA Version

KSP 1.4.3
BDA 1.2.1

OS / ENVIRONMENT

Windows 10

SUMMARY
When deploying flares above 300 m the flares will follow the aircraft as if formation flying and then disappear.  Regardless of how many flares, the effect is the same.

STEPS TO REPRODUCE

Attach a flare dispenser to any aircraft, then climb to above 300 m, then dispense flares and turn, watch the flares follow.

This issue was prevalent in KSP 1.3.1 and before and had other issue reports, but the problem still persists.

**Comment by TheKurgan** [comment]
I could be wrong, but the flares are only an animation, and the animation is tied to it's launcher. But that's my guess.

**Comment by jrodrigv** [comment]
@Gedas-S I did try a lot of different things but none of them made the particles any better to be honest.

It would be nice if you can give a try, maybe you can find a fix for it :)

**Comment by TheDogKSP** [comment]
Throwing in my 2cents here...
As you can see in #171 I also had the theory of floatingorigin shift causing the problem, but eventually I could blow up myself with cluster bombs (so real physical objects, not just particles from a particle system!) even when flying slowly and no FO shift happened...

But my follow-on theory about wrongly parented transforms also didnt turn out to be valid.

**Comment by Gedas-S** [comment]
@TheDogKSP FO shift can happen on vessel switch too (e.g. when the focused bomb explodes and focus reverts to the launching vessel).

KSP does not care about physical objects - if it ain't a vehicle, `FloatingOrigin` will probably ignore it. And since submunitions are only `GameObject`, KSP will happily disregard them when shifting your vehicle back to zero coords.

Btw, there's a small util for detecting FO shifts, it will come up on Debug Labels if you compile BDA with the `DEBUG` compiler flag on.

**Comment by flywlyx** [comment]
Any ParticleEmitter use "simulate world space" option will have this issue.
I think there is a way to work around.
Flares particle emitter is held by a new object to simulate the speed and location and not using "simulate world space". When you active a flare, the new game object moves with the same speed and create a PE with it.
