### ISSUE TITLE
Something's wrong with missile hitboxes...

### ISSUE THREAD

**Issue by TheDestroyer111** [PapaJoesSoup/BDArmory#52]
According to Kerbal Inventory System (a mod), the AGM-86C, which is one of (if not the) largest missile in BDArmory, has a volume of 2151 (2k) liters. Now the HARM, which has a the biggest wingspan when placed as a normal part (KIS shouldn't, and properly doesn't detect the folding wings of AGM-86), has 10535 (10k) liters of volume. WTF? This is important as volume counts how much stuff can fit into a container.

**Comment by Wraith977** [comment]
I'm not sure how KIS calculates volume, I would presume it just takes the dimensions of a part and puts them into a v=l*b*h formula to get the volume. I'm also not sure if it uses the collider's  or the model's dimensions (if it uses the collider's it may be a πr^2xh formula to calculate the volume) but this is what I get. (The rescale factor for both of these parts is 1)

AGM-86 (without wings)
model: x=5.032, y=0.595, z=0.503, v=1.506
collider: x=4.960, y=0.47, z=0.47, v=1.09

HARM
Model: x=4.037, y=1.142, z=1.142, v=5.265
collider: x=3.8, y=0.252, z=0.252, v=0.241

Using that I can assume that KIS uses the model's dimensions.

AGM-86 volume / HARM volume
KIS: 10535/2151=4.898
Me: 5.265/1.506=3.496

So if KIS used a simple v=l*b*h formula you should be able to fit 3.496 AGM-86 missiles for every HARM in a storage unit but KIS must be doing something else along the line. I presume you thought that KIS takes the "actual" volume of a part, not using dimensions to work out the volume because without the wings you should be able to fit ~4 AGM-86 missiles for every HARM. Nevertheless this is more an issue for KIS, not BDA I think, there's nothing to be done here that wouldn't require changing what the missiles actually look like (eg. shortening the wings on the HARM).

**Comment by TheDestroyer111** [comment]
Thing is, I would like to have some missiles on lets say a cargo ship/plane or an airbase without getting the part count to hell (AFAIK KIS-stored items don't take so much memory as placed parts do as no physics is counted for them). And I mean some other missiles than just hellfire and TOW which have short or folding wings. But yeah, I think this is more of a KIS issue than BDA.
p.s. i NEED ose workshop

**Comment by Kerbas-ad-astra** [comment]
It is possible to override the volume calculated by KIS (which does use L x W x H, basically querying some stock method to get the bounding-box dimensions and going from there) -- see e.g. Surface Experiment Package for examples of how.

**Comment by TheDestroyer111** [comment]
Yep. You can override the volume of a part for KIS by pasting the following:
`    MODULE
    {
        name = ModuleKISItem
        volumeOverride = 50
        stackable = false
        allowStaticAttach = 1
        staticAttachBreakForce = 2000
    }`
Into the part's .cfg file. Unfortunately this requires either messing with the game files manually, or ModuleManager. And I think there is a reason why BahamutoD didn't use MM to make his mod ;)
