### ISSUE TITLE
disparity between configured rounds per min and actual RPM

### ISSUE THREAD

**Issue by SpannerMonkey** [PapaJoesSoup/BDArmory#524]
- Bug Report
KSP and BDA Version
KSP 1.4.3
BDA 1.2.1 and previous 
##### OS / ENVIRONMENT
All
##### SUMMARY
Disparity between actual configured rounds per min and actual RPM
Quad bofors is cfg'd to fire 330 rpm , it overheats at 100 shots and pauses for a couple of seconds,   Just  , single shot fires 4 rounds ,  auto for 1min should be 330 shots  minus the overheat pause, , so say at max 300 .
However timed trials show that  it's actually  740 shots.    2400 start resource   1660 end resource   , Green clock,   retesting gives a slightly different number each time,  the variance is around 120 shots

**Comment by Gedas-S** [comment]
Pretty sure RPM is currently how often weapon fires, and does not take into account the number of shots it fires. Also, iirc currently there is no interpolation in firing time. A gun is either ready to fire, or is not ready to fire.

Regarding the second one, Unity does 50 updates per second, so the update interval is 0.02 seconds. A gun set to fire at an rpm of 1200 has an interval of 0.05 seconds. Since at 0.04 the gun is not yet ready to fire, the interval actually becomes 0.06 seconds, which gives us an effective RoF of 1000 rpm times number of fire transforms. This doesn't explain all the variance, but does explain some of it.
https://github.com/PapaJoesSoup/BDArmory/blob/1b076fb08b021330271a48cd38c7e5465a6d6d97/BDArmory/ModuleWeapon.cs#L974

Were the tests done in salvo or barrage mode? Barrage mode may introduce some delays in firing. You probably cannot change it for one gun in the UI, but you should be able to in the editor. Also, I wonder if changing the firing delay in BDA config would make a difference (the time between clicking the mouse and the gun firing).

**Comment by PapaJoesSoup** [comment]
Where are we at on this issue?

**Comment by Gedas-S** [comment]
Guns should now fire at the configured rpm times fire transforms. Guns can now fire multiple times per fixed update. Hangar readout should display the properly multiplied rpm (transforms * rpm).

This should fix the issue reported by @SpannerMonkey, not sure if this addresses the disparity reported by @Wraith977
