### ISSUE TITLE
Weapons arent showing up

### ISSUE THREAD

**Issue by GiskardRevenlov** [PapaJoesSoup/BDArmory#580]
##### ISSUE TYPE

 - Bug Report   (Something is broken)
 

##### SUMMARY

Like the title says all weapons from the mod are missing, I have a few structural parts but thats it, Ive tried reinstalling a few times but nothing has changed, nothing else seems wrong

**Comment by YasenWang** [comment]
I have the same problem and I try to change the weapon's "*.cfg" 
"mesh = xxx.mu" to "model = xxx/xxx/xxx"
It doesn't work. I want to know how to fix it.

**Comment by Gedas-S** [comment]
In order to have any hope of helping you we need:
- Log files
- BDA version
- OS version
- KSP version
- KSP language
- A screenshot of where you placed the BDA files in your GameData folder would also be helpful

As listed in the template you get when creating a new issue. :)

Because without these, we do not know what is going on on your computer, BDA works just fine on mine. :)

**Comment by YasenWang** [comment]
BDA version ：1.2.2.2
Windows 10.0
KSP version is the latest version download on steam 1.4.5
language both English and Chinese have the same problem.

I put folder BDArmory in GameData/(just one "GameData")


The game goes fine, so i don't have crash log, it just can't show all the parts in game.
Only some EMP weapons and 3 to ground radar were shown.(witch create new）

I guess the problem may caused by losing some other mods such as "bahaSP".
So I hope you could give me all the folders and files witch could add BDA in a new clean KSP.

**Comment by YasenWang** [comment]
my Email : 00000000@wangyusheng.cn
Thank you!

**Comment by Gh0stReaper123** [comment]
Every time the game is played, a log file is created. Go to your KSP folder where KSP.exe is located and send us KSP.txt.

**Comment by YasenWang** [comment]
[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/2441493/KSP.log)
This is my KSP.log

**Comment by YasenWang** [comment]
![path](https://user-images.githubusercontent.com/30994456/46455934-9cf90500-c7df-11e8-8e15-67cf0b27f67b.png)
I don't know whether my folder has all depended mods or not. So I upload my GameData fold.
Hope you could check out the problem.
Thanks!

**Comment by TheDogKSP** [comment]
Your install and ksp.log looks fine.
Don't you see the parts tab "BDarmory" in the SPH/VAB editor?
Can you post  a screenshot of inside the SPH/VAB with the bdarmory tab selected?

**Comment by TheDogKSP** [comment]
Very weird. According to your log file all bdarmory parts were loaded successfully.... Mmhhhh...

Just to rule out it's not a problem with the localisation file, please try this:

Delete file localization-zh-cn.cfg from gamedata/bdarmory/localization

Afterward all texts will be missing, but if more parts show up then it means there is a problem with our texts...
