### ISSUE TITLE
Flare and Gun Exhaust floating with the Craft.

### ISSUE THREAD

**Issue by Temptatiions** [PapaJoesSoup/BDArmory#72]
![20161102192908_1](https://cloud.githubusercontent.com/assets/23227080/19954159/04049424-a133-11e6-8004-5bcbf0d7983f.jpg)

They float around as if I were near the 700 m/s mark when the world moves around the craft. They are also causing major FPS drops, and caused the game to crash. Did not occur with chaff however.

Also tested on fresh install:
![20161102193943_1](https://cloud.githubusercontent.com/assets/23227080/19954288/3dc180e0-a134-11e6-9018-b9038e2d4373.jpg)

**Comment by gomker** [comment]
@Temptatiions  this issue seems to be related to #74 
I would like to consolidate them into one for easier tracking.  Can you update that issue with the following info 

version of KSP
version of BDA
OS Build and Version
Link to a full KSP log if reporting a problem
See this for more information
http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/
