### ISSUE TITLE
BDArmory does not add parts.

### ISSUE THREAD

**Issue by BraveCaperCat2** [PapaJoesSoup/BDArmory#827]
When reporting issues please provide the following information:

[See this for more information on reporting issues for KSP Mods](http://forum.kerbalspaceprogram.com/?showtopic=83212)

[See the Original Forum Post (OP) for additional info](http://forum.kerbalspaceprogram.com/?showtopic=155014)

##### ISSUE TYPE

 - Bug Report   (Something is broken)

##### KSP and BDA Version

```
KSP: 1.12.5 (latest version)
BDArmory: 0.2.2.1 (according to bdarmory.version file inside mod)
```

##### OS / ENVIRONMENT
Windows 11
KSP: Steam
##### SUMMARY

There are no parts or categories added by the mod inside KSP - there is only 1 GUI added.
##### STEPS TO REPRODUCE
Launch the specified version of BDArmory with all dependencies - look in parts menu and it is not there.

##### Log Files

[KSP.log](https://github.com/PapaJoesSoup/BDArmory/files/11301478/KSP.log)

Output.txt files non-existant.

[Mod Files](https://drive.google.com/u/0/uc?id=18RSbh8Q5sQdOUHTruhGaCdYop3CjqOAc&export=download) - 613 MB are too large and I do not know how to use "gist.github.com"

**Comment by PapaJoesSoup** [comment]
Wrong version of BDArmory installed.

**Comment by BraveCaperCat2** [comment]
> Wrong version of BDArmory installed.

Latest version available on curseforge/spacedock (not sure which)

**Comment by PapaJoesSoup** [comment]
Latest beta is on GitHub releases.  I do suggest bdarmory+Sent from Android Mobile-------- Original Message --------Subject: Re: [PapaJoesSoup/BDArmory] BDArmory does not add parts. (Issue #827)From: BraveCaperCat2 To: PapaJoesSoup/BDArmory CC: Joseph Korinek ,State change 

Wrong version of BDArmory installed.

Latest version available on curseforge/spacedock (not sure which)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/PapaJoesSoup/BDArmory/issues/827#issuecomment-1520450520",
"url": "https://github.com/PapaJoesSoup/BDArmory/issues/827#issuecomment-1520450520",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
