### ISSUE TITLE
ECM Jammer Balance

### ISSUE THREAD

**Issue by gomker** [PapaJoesSoup/BDArmory#84]
Start looking at how to balance ECM Jammer power

**Comment by TheDestroyer111** [comment]
I think there should be a separate part for a "self-protection jammer" and the full-size jammer. The self-protect jammer is a small jammer placed on most modern military fighters to give them additional countermeasures against radar guided missiles. I think this jammer should work in a very similar way as the current jammer (maybe a bit rebalanced), just be smaller-sized (a bit bigger than ai pilot computer) and weigh 0.1 tonne or maybe a bit less (the current jammer weighs 0.3 tonne). Aside from the self-protect jammer, the current one should have its jamming capabilities totally reworked. My idea is that the  full-sized jammer should use something around 20 ec/s (maybe more, but that would bring other balance issues, so 20 ec/s is a good compromise between usability on larger and smaller craft) and instead of simply making it harder to lock on the jamming guy for all his enemies, it should be able to just completely jam the radars of all enemies in a specific direction for the time when it is working (with a maybe 10 degree angle error tolerance in all directions), but do nothing against enemies that are in a different direction. All this on the full-size jammer chould come with some ability to automatically track the opponent's movements if the enemy is locked on by a targeting device. Needless to say, the direction in which jamming is done should be kept relative to the ground, rather than relative to the aircraft carrying a jammer.

**Comment by gomker** [comment]
Notes on code research

      [KSPField] public float jammerStrength = 700;
      [KSPField] public float lockBreakerStrength = 500;
      [KSPField] public float rcsReductionFactor = 0.75f;

            //unlock if over-jammed
            if (lockedTarget.vesselJammer &&
                lockedTarget.vesselJammer.lockBreakStrength >
                lockedTarget.signalStrength*lockedTarget.vesselJammer.rcsReductionFactor)
            {
                //UnlockAllTargets();
                UnlockTargetAt(index, true);
                return;
            }

jammerStrength is configured in the ECMJammer part config. lockBreakerStrength seems to be hard coded 

rcsReductionFactor is based on mass

                if (jammer.rcsReduction)
                {
                    rcsrTotalMass += jammer.part.mass;
                    rcsrTotal += jammer.rcsReductionFactor;
                    rcsrCount++;
                }
As you can see the "signalStrength" is multiplied , vessels up close will will have a high number there. Plan is to maybe make the lockBreakerStrength a param too, and we can find out what balances it out.

**Comment by jrodrigv** [comment]
Without going into details. I would like to make the ECM Jammer more user
friendly from an  "arcade" point of view.

Have you ever played Battlefield 3 or 4? When a jet activates the ECM it
becomes unlockeable during 10 seconds, then it has a cool-down time of 60s.
(I'm thinking that when more than one ECM is available then you can active
2 ECM, one after the other)

It is as easy as that! Besides,  I would like to show an "effect" as BF3
does when the target jet has activated the ECM.

2016-11-13 22:08 GMT+01:00 Derek Lane <notifications@github.com>:

**Comment by Guard13007** [comment]
If you're going to do that, please make it as a separate system or optional.. :(

**Comment by jrodrigv** [comment]
I'm not going to do any work on this until we reach an agreement. This issue was related with ECM Jammer balance. And in my opinion, the current ECM is almost useless. 

I guess that when a user is playing with the ECM for the first time, they will be expecting something powerful, that means if activated no one can lock on me or if a missile is already locked it will break the lock automatically.

**Comment by gomker** [comment]
My thoughts were adding a slider that would adjust the Jammer Strength allowing the user to pick how powerful it could be. Or we could add a multiplier in the BDA Menu that the user could adjust how easy/hard it is to break a radar lock.

**Comment by demonfiren** [comment]
@jrodrigv As average user: no, not what I expected. I expected the standard three-quarters realism, and I got just that.

**Comment by TheDogKSP** [comment]
IMHO, the jammer is currently quite useless, and quite unintuitive.

I see basically 2 options here (this also applies to some other sections/sub-systems of BDA):

A) Strive for realism. Jamming would continue to work by reducing the computed radar cross section of a plane by some degree. This needs to be calculated in real-time (or at least periodically), for each vessel against all enemy radar sources. 

B) Strive for accessibility. That goes for a more arcade-style system, as jrodrigv described.  It is not realistic, but it is easy to understand & use.


From my point of view, the key would be to decide this direction not for single sub-systems individually, but for BDAc as a whole for the refactoring/rewrite.
I see lots of benefits for going with a simpler system: code complexity, runtime performance, ease-of-use.
Maybe the "cannot lock for 10 seconds" mode is TOO arcade-y. And I dont have great ideas myself at the moment, just my 2 cents...

**Comment by jrodrigv** [comment]
@TheDogKSP I totally agree with you. I would like to add that in my opinion the final goal is to make something that most part of BDArmory users want to use  because it is usable and funny :)

I love realism (I used to play Realism Overhaul mod) but I'm a senior software engineer as well...and I know what realism means when we are talking about real-time complex calculations, that means lag, performance issues, memory issues, etc... but the biggest problem is that not all users will understand what is going on or how it works!

We will need to do some trade-offs to make everyone happy and the same time provide something usable, funny and awesome :)

**Comment by Guard13007** [comment]
I was going to say go for realism, but yea, it does mean more performance issues. That and I can't focus on targeting and dodging at the same time as it is right now. I still think that particular idea "can't lock for 10 seconds" is taking it too far though.

**Comment by jrodrigv** [comment]
Maybe we can still using the same process "reduce of resolution of the radar camera counting black points"   but we can reduce it much more during more time so you can't lock it at all. 

Also I would like to check if the size of the vessel is relevant from a code point of view when a lock is calculated. I think it should be easier to lock a bigger vessel.

**Comment by Guard13007** [comment]
I love that idea! :D

**Comment by TheDogKSP** [comment]
v1.0.0 released, closing this issue
