### ISSUE TITLE
AI will fire when plane is in maneuvering routine

### ISSUE THREAD

**Issue by gomker** [PapaJoesSoup/BDArmory#85]
Need to review routines for AI in combat against ground targets. I can recreate scenarios that cause the AI to fire while pointing away from the target (180 deg) 

From what I can see is the plane starts targeting , then the AI engages turns to gain altitude however, it will fire a Laser or GPS guided weapon in opposite direction, seemingly unaware it was doing a maneuver.  I suspect the coroutines involved are not aware of each other's execution state

**Comment by jrodrigv** [comment]
I've seen similar using GPS targeting. Inmediatly after take off my plane fired a gps missile ( the target plane was on  >90 angle vector from the current missile/vessel transform forward vector. BTW The missile hit the target :)

**Comment by DoctorDavinci** [comment]
When recording the second tier of the BAD T2 tournament I noticed that whenever a craft on one team targets a craft on the opposing team the AI will fire off one shot. This would happen whenever the AI switched targets or just acquired a target

I'm wondering if this may be a symptom of the same issue ... You can see it happening in the videos in this playlist: https://www.youtube.com/playlist?list=PLm0VtvicwleDA3W2oDLEy6MbcgT6ETq2X

**Comment by Hector919** [comment]
This issue still seems to be present, I've also encountered it while testing a multirole CAP/CAS fighter. I placed three target drones left of the runway, ordered the jet to take off and during the extending  phase (while not having a laser lock onto any target) it already started firing its HARM and hellfire missiles. It fired one missile about every three to six seconds until it was out of ammunition, at which point it resolved to utterly annihilate one drone with surprising precision before the last two hellfires (they managed to get a lock as the plane could turn quite quick towards the drones) stirred up the pile of debris.
after that, the jet attempted to bomb the drones with varying succes, partially due to excessive rolling as outlined in issue #173 .

**Comment by DoctorDavinci** [comment]
Here are my testing notes in regards to FLIR Ball/Targeting Pod orientation as requested ......
------------------------------------------------------------------
I conducted 2 tests ..........

**1**- FLIR Ball oriented in the direction of travel in which it was found that there was no possibility of getting a lock, therefore no firing of missile - Green DigiCam drone in video
**2**- FLIR Ball oriented facing the ground in which it was found that once a lock was attained there was a missile launch - Orange DigiCam drone in video

This leads me to believe 2 things ........

**1**- that as soon as the Weapon Manager has a lock it will fire
**2**- the camera lens on the FLIR Ball/Targeting Pod is the front of these parts and they both need to be pointed towards the direction of travel (front of the craft) otherwise if you get a lock behind you the Weapon Manager will fire 

Video of tests: https://youtu.be/TlWBxR5k7j4

This leads me to conclude that the FLIR Targeting Ball as well as the FLIR Targeting Pod MUST be pointed in the general direction of travel for a given craft

**Comment by jrodrigv** [comment]
I'm going to close this because I haven't seen this behaviour for a long time.
