### ISSUE TITLE
Vulcan mass and drag

### ISSUE THREAD

**Issue by TheDestroyer111** [PapaJoesSoup/BDArmory#90]
The Vulcan Turret weighs 0.4 tons and Vulcan (Hidden) weighs 0.3 tons, that's unrealistic (plus also not scaled for KSP, but size is OK, just mass and drag are weird) and the real gun weighs about 100 kilograms (0.1 tons), depending on variant (slighly higher on A1 and slightly smaller on A2). Also the Vulcan has quite high drag - adding it to a craft capable of supercruise completely without using afterburners, ramjets, or rockets very often makes it unable to do so, while the shape of the cannon suggests that if placed in a reasonable way (stick to the surface of a plane) it should have little to no drag (for hell knows why, chaff and flare dispensers also have quite high drag, enough to prevent a little turbojet drone from supercruising, despite their low mass... maybe they have a high drag coefficient in their cfg) But as far as I know KSP's drag model, reducing their mass will also reduce drag (not the coefficient, but the actual value at given pressure/airspeed), so this won't be a big problem.
//EDIT: yeah. and btw i meant not just some random supersonic flight, but supersonic flight using panther engines _without_ afterburner.

**Comment by faelucc** [comment]
Hi,
Having an issue with drag on a small plane equiped with the hidden vulcan I did some checks using the "Display Aero Data in Action Menus" option. And there is the results, at 400 m/s (alt 300m):
* Drag from a vulcan: ~6.6
* Drag from a 20mm ammo box: ~22
* Drag from a chaft/flare dispenser: ~9
The vulcan seems to generate more drag than expected, but that's nothing compared to an ammo box!
A dispenser generating more than 14 "units" of drag at 600 m/s, removing the 2 ammo boxes and the 4 dispensers from my plane "solved" the issue (and i didn't remove the 2 vulcans). Of course, planes using the hidden vulcain have to use at least one ammo box, that's why we though the weapon was the issue :p

I tried to change the mass and drag values in the part ".cfg" file, but it did nothing.

The issue MAY come from the "DRAG_CUBE" values (generated at startup using the "model.mu" file? Just guessing...), even if we try to "hide" the parts by moving them into their parent parts...
Good luck fixing that :) Until then, as TheDestroyer111 said, it will be incredibly hard (or impossible) to maintain supersonic flight with dispensers and ammo boxes.

Thanks for reading :)

**Comment by TheDestroyer111** [comment]
And even if the ammobox has a glitched drag cube, fixing it won't change the fact that there is another issue: the vulcan is just too heavy, way heavier than in reality and if it is mounted on front of the plane it seriously impacts maneuverability by moving center of mass.

**Comment by Guard13007** [comment]
@TheDestroyer111 You must be making some very tiny planes for it to have that much impact, it seems fine to me.

**Comment by TheDestroyer111** [comment]
@Guard13007 What is your definition of a tiny plane? If it is any fighter aircraft with a typical single-seat fighter aerodynamic configuration, that is heavier than 15 tons, then its no wonder that mounting guns changes nothing. And BTW, you still don't consider it absurd once you find out that the hidden version of the Vulcan is 3 times heavier than the M230 30mm turret-based chaingun, which weighs 0,1 ton in BDA? And remember than in reality the Vulcan weighs 3 times less than it does in BDA.
OK, to avoid needless rageout and other crap, I'll just make a pull and see what the devs say :P

**Comment by Guard13007** [comment]
@TheDestroyer111 Can I see an example of a plane it causes you significant problems with? Maybe you're using mods I am unfamiliar with.

**Comment by TheDestroyer111** [comment]
@Guard13007, it gives problems on anything that is designed to use its guns as the main weapon, rather than missiles. Specifically, I mean aircraft based roughly on later German WWII planes.
But even if it doesn't cause any significant problems, can you please give me a reason to make it 3x heavier as in reality, while the M230 is 3x lighter than the current Vulcan even though the M230 is more powerful?

**Comment by Guard13007** [comment]
@TheDestroyer111 Balance within the realm of how KSP works and how the rest of BD Armory works.

**Comment by gomker** [comment]
Issue covered in pull request #117
